export const SONGS: Song[] = [
  {
    title: "The Older I Get",
    artists: ["Alan Jackson"],
    genres: ["country", "christian country", "classic country"],
    releaseYr: 2021,
  },
  {
    title: "Butter",
    artists: ["BTS"],
    genres: ["k-pop"],
    releaseYr: 2022,
  },
  {
    title: "Die With a Smile",
    artists: ["Bruno Mars", "Lady Gaga"],
    genres: ["pop", "art pop"],
    releaseYr: 2025,
  },
  {
    title: "Love Story",
    artists: ["Taylor Swift"],
    genres: ["pop"],
    releaseYr: 2008,
  },
  {
    title: "Viva la Vida",
    artists: ["Coldplay"],
    genres: ["alternative"],
    releaseYr: 2008,
  },
  {
    title: "Dangerously",
    artists: ["Charlie Puth"],
    genres: ["soft pop", "pop"],
    releaseYr: 2016,
  },
  {
    title: "Someone You Loved",
    artists: ["Lewis Capaldi"],
    genres: ["alternative", "soft pop"],
    releaseYr: 2019,
  },
  {
    title: "In The Stars",
    artists: ["Benson Boone"],
    genres: ["pop"],
    releaseYr: 2022,
  },
  {
    title: "Perfect",
    artists: ["Ed Sheeran"],
    genres: ["soft pop", "pop"],
    releaseYr: 2017,
  },
  {
    title: "Young and Beautiful",
    artists: ["Lana Del Rey"],
    genres: ["alternative"],
    releaseYr: 2013,
  },
  { title: "golden hour", artists: ["JVKE"], genres: ["pop"], releaseYr: 2022, },
  { title: "Night Changes", artists: ["One Direction"], genres: ["pop"], releaseYr: 2014, },
  { title: "How Do I Say Goodbye", artists: ["Dean Lewis"], genres: ["pop"], releaseYr: 2022, },
  { title: "BIRDS OF A FEATHER", artists: ["Billie Eilish"], genres: ["alternative"], releaseYr: 2024, },
  { title: "The Nights", artists: ["Avicii"], genres: ["edm", "dance"], releaseYr: 2015, },
  { title: "Memories", artists: ["Maroon 5"], genres: ["pop"], releaseYr: 2019, },
  { title: "Mojito", artists: ["Jay Chou"], genres: ["mandopop", "c-pop", "taiwanese pop", "gufeng", "cantopop", "chinese r&b"], releaseYr: 2022, },
  { title: "Snowman", artists: ["Sia"], genres: ["pop"], releaseYr: 2017, },
  { title: "Please Please Please", artists: ["Sabrina Carpenter"], genres: ["pop"], releaseYr: 2024, },
  { title: "City Of Stars", artists: ["Emma Stone", "Ryan Gosling"], genres: ["musicals", "drama"], releaseYr: 2016, },
  { title: "Firework", artists: ["Katy Perry"], genres: ["pop"], releaseYr: 2010, },
  { title: "I Ain’t Worried", artists: ["OneRepublic"], genres: ["pop", "soft pop"], releaseYr: 2022, },
  { title: "Ordinary", artists: ["Alex Warren"], genres: ["pop"], releaseYr: 2025, },
  { title: "Pink Venom", artists: ["BLACKPINK"], genres: ["k-pop"], releaseYr: 2022, },
  { title: "Stitches", artists: ["Shawn Mendes"], genres: ["pop"], releaseYr: 2015, },
  { title: "Love wins all", artists: ["IU"], genres: ["k-pop", "k-ballad"], releaseYr: 2024, },
  { title: "Can't Stop the Feeling!", artists: ["Justin Timberlake"], genres: ["pop"], releaseYr: 2016, },
  { title: "Boyfriend", artists: ["Justin Bieber"], genres: ["pop"], releaseYr: 2012, },
  { title: "deja vu", artists: ["Olivia Rodrigo"], genres: ["pop"], releaseYr: 2021, },
  { title: "Wrecking Ball", artists: ["Miley Cyrus"], genres: ["pop"], releaseYr: 2013, },
  { title: "Into You", artists: ["Ariana Grande"], genres: ["pop"], releaseYr: 2016, },
  { title: "blue", artists: ["yung kai"], genres: ["alternative"], releaseYr: 2025, },
  { title: "Set Fire to the Rain", artists: ["Adele"], genres: ["pop", "soft pop"], releaseYr: 2011, },
  { title: "Believer", artists: ["Imagine Dragons"], genres: ["alternative"], releaseYr: 2017, },
  { title: "Because Of You", artists: ["Kelly Clarkson"], genres: ["pop"], releaseYr: 2004, },
  { title: "Falling", artists: ["Harry Styles"], genres: ["pop"], releaseYr: 2019, },
  { title: "Merry-Go-Round of Life", artists: ["Joe Hisaishi"], genres: ["soundtrack", "japanese classical", "anime"], releaseYr: 2004, },
  { title: "Brave", artists: ["Sara Bareilles"], genres: ["pop"], releaseYr: 2013, },
  { title: "House Party", artists: ["Sam Hunt"], genres: ["country", "pop country"], releaseYr: 2014, },
  { title: "You Raise Me Up", artists: ["Josh Groban"], genres: ["pop"], releaseYr: 2003, },
  { title: "Rise Up", artists: ["Andra Day"], genres: ["soft pop", "r&b", "soul"], releaseYr: 2015, },
  { title: "Can't Help Falling in Love", artists: ["Elvis Presley"], genres: ["rock", "rock and roll"], releaseYr: 1961, },
  { title: "Never Enough", artists: ["Loren Allred"], genres: ["pop"], releaseYr: 2017, },
  { title: "Summer Forever", artists: ["Billy Currington"], genres: ["country", "acoustic country"], releaseYr: 2015, },
  { title: "I Want It That Way", artists: ["Backstreet Boys"], genres: ["pop"], releaseYr: 1999, },
];